import type { Model, ModelProvider } from './types.js';

/**
 * Portable local model configuration.
 *
 * The point of this format is that a user can move their local setup between
 * machines, or check it into a project, without moving anything sensitive. Two
 * rules follow from that and are enforced rather than documented:
 *
 *   - The export carries no credential material of any kind. Local runtimes
 *     mostly need none, but a provider record can hold an API-key reference or
 *     an environment-variable name, and neither belongs in a portable file.
 *     The exporter builds each entry from an explicit field list, so a field
 *     added to the entity later cannot leak into the export by default.
 *   - The import trusts nothing. A configuration file is untrusted input — it
 *     may have been edited by hand, generated by an agent, or fetched from a
 *     repository — so every endpoint, provider kind, and name is revalidated
 *     against the same rules the registration API applies.
 */

export const LOCAL_CONFIG_VERSION = 1 as const;

export interface LocalProviderConfig {
  providerKind: string;
  name: string;
  endpoint: string;
}

export interface LocalModelConfig {
  providerKind: string;
  endpoint: string;
  modelName: string;
  name: string;
  quantization?: string;
  license?: string;
  sizeBytes?: number;
  /** Recorded for reference only; an import never treats it as verified. */
  artifactSha256?: string;
}

export interface LocalConfigDocument {
  version: typeof LOCAL_CONFIG_VERSION;
  exportedAt: string;
  providers: LocalProviderConfig[];
  models: LocalModelConfig[];
}

export type ConfigRejection =
  | 'config_version_unsupported'
  | 'config_malformed'
  | 'provider_kind_unsupported'
  | 'endpoint_not_local'
  | 'model_name_missing'
  | 'provider_missing_for_model';

/** Fields copied into an export. Anything not listed here never leaves. */
const PROVIDER_EXPORT_FIELDS = ['providerKind', 'name', 'endpoint'] as const;

export function exportLocalConfig(
  providers: ModelProvider[],
  models: Model[],
  now: () => string = () => new Date().toISOString(),
): LocalConfigDocument {
  const localProviders = providers.filter((provider) => Boolean(provider.endpoint));
  const byId = new Map(localProviders.map((provider) => [provider.id, provider]));

  return {
    version: LOCAL_CONFIG_VERSION,
    exportedAt: now(),
    providers: localProviders.map((provider) => {
      // Built field by field on purpose: a spread would carry every future
      // field, including any that later holds a secret reference.
      const entry: LocalProviderConfig = {
        providerKind: String(provider[PROVIDER_EXPORT_FIELDS[0]]),
        name: String(provider[PROVIDER_EXPORT_FIELDS[1]]),
        endpoint: String(provider[PROVIDER_EXPORT_FIELDS[2]]),
      };
      return entry;
    }),
    models: models
      .filter((model) => model.local && byId.has(model.providerId))
      .map((model) => {
        const provider = byId.get(model.providerId)!;
        const entry: LocalModelConfig = {
          providerKind: provider.providerKind,
          endpoint: provider.endpoint ?? '',
          modelName: model.modelName,
          name: model.name,
        };
        if (model.quantization) entry.quantization = model.quantization;
        if (model.license) entry.license = model.license;
        if (typeof model.sizeBytes === 'number') entry.sizeBytes = model.sizeBytes;
        if (model.artifactSha256) entry.artifactSha256 = model.artifactSha256;
        return entry;
      }),
  };
}

export interface ParsedLocalConfig {
  ok: boolean;
  rejections: Array<{ reason: ConfigRejection; detail?: string }>;
  providers: LocalProviderConfig[];
  models: LocalModelConfig[];
}

/**
 * Validate an incoming configuration document.
 *
 * `isLocalEndpoint` and `isSupportedKind` are injected rather than imported so
 * this stays a pure function testable without the provider registry, and so
 * the import cannot drift from whatever the registration API considers valid.
 */
export function parseLocalConfig(
  input: unknown,
  isSupportedKind: (kind: string) => boolean,
  isLocalEndpoint: (endpoint: string) => boolean,
): ParsedLocalConfig {
  const rejections: ParsedLocalConfig['rejections'] = [];
  const providers: LocalProviderConfig[] = [];
  const models: LocalModelConfig[] = [];

  if (!input || typeof input !== 'object' || Array.isArray(input)) {
    return { ok: false, rejections: [{ reason: 'config_malformed' }], providers, models };
  }
  const document = input as Record<string, unknown>;

  if (document.version !== LOCAL_CONFIG_VERSION) {
    // Refuse an unknown version rather than importing it optimistically: a
    // future format may mean something different by the same field names.
    return {
      ok: false,
      rejections: [{ reason: 'config_version_unsupported', detail: String(document.version) }],
      providers,
      models,
    };
  }

  const rawProviders = Array.isArray(document.providers) ? document.providers : null;
  const rawModels = Array.isArray(document.models) ? document.models : null;
  if (!rawProviders || !rawModels) {
    return { ok: false, rejections: [{ reason: 'config_malformed' }], providers, models };
  }

  const acceptedEndpoints = new Set<string>();
  for (const candidate of rawProviders) {
    if (!candidate || typeof candidate !== 'object') {
      rejections.push({ reason: 'config_malformed' });
      continue;
    }
    const entry = candidate as Record<string, unknown>;
    const providerKind = String(entry.providerKind ?? '');
    const endpoint = String(entry.endpoint ?? '');
    if (!isSupportedKind(providerKind)) {
      rejections.push({ reason: 'provider_kind_unsupported', detail: providerKind });
      continue;
    }
    if (!isLocalEndpoint(endpoint)) {
      // A configuration file naming a remote endpoint would turn a "local
      // model" import into an outbound connection, so it is refused outright.
      rejections.push({ reason: 'endpoint_not_local', detail: endpoint });
      continue;
    }
    providers.push({
      providerKind,
      endpoint,
      name: String(entry.name ?? `${providerKind} local`).slice(0, 200),
    });
    acceptedEndpoints.add(`${providerKind}|${endpoint}`);
  }

  for (const candidate of rawModels) {
    if (!candidate || typeof candidate !== 'object') {
      rejections.push({ reason: 'config_malformed' });
      continue;
    }
    const entry = candidate as Record<string, unknown>;
    const providerKind = String(entry.providerKind ?? '');
    const endpoint = String(entry.endpoint ?? '');
    const modelName = String(entry.modelName ?? '')
      .trim()
      .slice(0, 200);
    if (!modelName) {
      rejections.push({ reason: 'model_name_missing' });
      continue;
    }
    if (!acceptedEndpoints.has(`${providerKind}|${endpoint}`)) {
      // Never invent a provider for an orphan model: that would silently
      // create a registration the document never actually described.
      rejections.push({ reason: 'provider_missing_for_model', detail: modelName });
      continue;
    }
    const model: LocalModelConfig = {
      providerKind,
      endpoint,
      modelName,
      name: String(entry.name ?? modelName).slice(0, 200),
    };
    if (typeof entry.quantization === 'string') {
      model.quantization = entry.quantization.slice(0, 64);
    }
    if (typeof entry.license === 'string') model.license = entry.license.slice(0, 64);
    if (typeof entry.sizeBytes === 'number' && Number.isInteger(entry.sizeBytes)) {
      model.sizeBytes = entry.sizeBytes;
    }
    // A digest in a configuration file is a claim, not evidence. It is carried
    // for reference and never marks the artifact verified; only a real import
    // against bytes on disk can do that.
    if (typeof entry.artifactSha256 === 'string' && /^[0-9a-f]{64}$/i.test(entry.artifactSha256)) {
      model.artifactSha256 = entry.artifactSha256.toLowerCase();
    }
    models.push(model);
  }

  return { ok: rejections.length === 0, rejections, providers, models };
}

/** Guard against a secret reaching an export, whatever the entity shape becomes. */
const SECRET_FIELD = /(secret|token|key|password|credential|authorization)/i;

export function containsSecretField(value: unknown, path: string[] = []): string | null {
  if (!value || typeof value !== 'object') return null;
  for (const [field, child] of Object.entries(value as Record<string, unknown>)) {
    if (SECRET_FIELD.test(field)) return [...path, field].join('.');
    const nested = containsSecretField(child, [...path, field]);
    if (nested) return nested;
  }
  return null;
}
